---
apiVersion: v1
kind: Pod
metadata:
 name: ashusamplepod

spec:
 containers:
  - image: nginx
    name: c1
    ports:
     - containerPort: 80
    imagePullPolicy: IfNotPresent   #  this is optional 
